import type { KgEntity } from '../../types/domain';
import { daysAgo } from '../mockHelpers';

export const coverageAuthModuleEntity: KgEntity = {
  id: 'coverage_auth_module',
  name: 'Auth module coverage report',
  domain: 'tests_quality',
  entityType: 'Coverage Report',
  summary: '81% line coverage; negative-path and abuse-case branches under-covered.',
  sourceSystem: 'Jest / Pytest Test MCP',
  owner: 'Test Generation Agent',
  confidenceScore: 0.88,
  lastUpdated: daysAgo(1),
  projectId: 'proj_checkout_service',
  relationships: [],
  evidenceRefs: ['coverage_report_auth_2026_08_26.json'],
  provenance: 'Generated by test_generation_agent from the latest test run.',
  relatedAgentActivity: ['test_generation_agent generated this report 1 day ago'],
};
