import type { CrossPhaseInsight } from '../types/domain';

// Demo insights. In production these are generated by agents traversing the
// Knowledge Graph across phase boundaries — never hand-authored.
export const crossPhaseInsights: CrossPhaseInsight[] = [
  {
    id: 'insight_1',
    summary: 'Three new stories touch the authentication module, which has two open CVEs and four technical-debt items.',
    relatedEntityIds: ['auth_module', 'cve_auth_2024_1111', 'cve_auth_2024_2222'],
    severity: 'warning',
  },
  {
    id: 'insight_2',
    summary: 'This pull request changes a module with high bug recurrence; deeper QA scanning is recommended.',
    relatedEntityIds: ['pr_auth_mfa_enroll'],
    severity: 'warning',
  },
  {
    id: 'insight_3',
    summary: 'An incident root cause is linked to a technical-debt item filed six sprints ago.',
    relatedEntityIds: ['incident_auth_outage_0417', 'debt_auth_session_store'],
    severity: 'info',
  },
  {
    id: 'insight_4',
    summary: 'A deployment uses an artifact with unverified provenance and a privileged service account.',
    relatedEntityIds: ['deploy_checkout_prod_v482'],
    severity: 'critical',
  },
];
