// Vercel serverless function backing the live Remediation Agent action.
//
// This is the one deliberately "real" integration in an otherwise all-mock
// application: given a whitelisted finding id, it opens (or reuses) an
// actual draft pull request on GitHub. It never accepts free-form repo
// targets or file content from the client — only a known finding id.
//
// Required env var: GITHUB_TOKEN — a fine-grained PAT scoped to this repo
// with Contents: Read and write + Pull requests: Read and write.
// Optional env vars: GITHUB_OWNER, GITHUB_REPO (default to this repo),
// DEMO_TRIGGER_SECRET (if set, requests must send it as x-demo-secret).

import {
  createBranch,
  createPullRequest,
  findOpenPullRequestForBranch,
  getBranchHeadSha,
  getFileSha,
  getRepo,
  putFile,
} from './_lib/github.js';
import { KNOWN_FINDINGS } from './_lib/findings.js';

interface MinimalRequest {
  method?: string;
  headers: Record<string, string | string[] | undefined>;
  body?: unknown;
}

interface MinimalResponse {
  status(code: number): MinimalResponse;
  json(body: unknown): void;
}

function readSecretHeader(req: MinimalRequest): string | undefined {
  const value = req.headers['x-demo-secret'];
  return Array.isArray(value) ? value[0] : value;
}

function parseBody(body: unknown): Record<string, unknown> {
  if (!body) return {};
  if (typeof body === 'string') {
    try {
      return JSON.parse(body);
    } catch {
      return {};
    }
  }
  return body as Record<string, unknown>;
}

export default async function handler(req: MinimalRequest, res: MinimalResponse) {
  if (req.method !== 'POST') {
    res.status(405).json({ ok: false, error: 'Use POST.' });
    return;
  }

  const expectedSecret = process.env.DEMO_TRIGGER_SECRET;
  if (expectedSecret && readSecretHeader(req) !== expectedSecret) {
    res.status(401).json({ ok: false, error: 'Missing or invalid demo trigger secret.' });
    return;
  }

  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    res.status(500).json({
      ok: false,
      error: 'Live GitHub integration is not configured yet. Set GITHUB_TOKEN in the Vercel project environment variables.',
    });
    return;
  }

  const { findingId } = parseBody(req.body);
  const finding = typeof findingId === 'string' ? KNOWN_FINDINGS[findingId] : undefined;
  if (!finding) {
    res.status(400).json({ ok: false, error: `Unknown or missing findingId. Known ids: ${Object.keys(KNOWN_FINDINGS).join(', ')}` });
    return;
  }

  const owner = process.env.GITHUB_OWNER || 'vepopuri';
  const repo = process.env.GITHUB_REPO || 'secure_sdlc';
  const branch = `remediation-agent/${finding.id.replace(/_/g, '-')}`;
  const path = `remediation/${finding.id}.md`;

  try {
    const repoInfo = await getRepo(token, owner, repo);
    const base = repoInfo.default_branch;

    let branchSha = await getBranchHeadSha(token, owner, repo, branch);
    let createdBranch = false;
    if (!branchSha) {
      const baseSha = await getBranchHeadSha(token, owner, repo, base);
      if (!baseSha) throw new Error(`Base branch "${base}" not found.`);
      await createBranch(token, owner, repo, branch, baseSha);
      branchSha = baseSha;
      createdBranch = true;
    }

    const existingFileSha = await getFileSha(token, owner, repo, path, branch);
    const generatedAt = new Date().toISOString();
    const content = `# Remediation: ${finding.title}

**Finding:** ${finding.cveId} — ${finding.module}
**Generated by:** Remediation Agent (live demo integration)
**Generated at:** ${generatedAt}

## Description

${finding.description}

## Proposed remediation

This is a template remediation note, not an AI-generated code patch. It
demonstrates the Remediation Agent's live write path — a real branch and a
real pull request on this repository — described in the platform's Agents
catalog. A future iteration wires this up to an actual model call that
proposes a real code diff for review.

## Next steps

1. A human reviewer confirms this finding is still open.
2. Replace this note with an actual patch (code + regression test).
3. Route the pull request through the platform's Level 2 (Controlled
   change) approval policy before merging.

---
_This file was created automatically by the Agentic SDLC Platform demo. It
is intentionally additive and safe to delete._
`;

    await putFile(
      token,
      owner,
      repo,
      path,
      branch,
      content,
      `Remediation Agent: draft note for ${finding.cveId}`,
      existingFileSha,
    );

    const existingPr = await findOpenPullRequestForBranch(token, owner, repo, branch);
    if (existingPr) {
      res.status(200).json({
        ok: true,
        reused: true,
        prUrl: existingPr.html_url,
        prNumber: existingPr.number,
        branch,
      });
      return;
    }

    const pr = await createPullRequest(
      token,
      owner,
      repo,
      branch,
      base,
      `Remediation: ${finding.title}`,
      `Automated draft opened by the **Remediation Agent** (live demo integration) for ${finding.cveId}.\n\n${finding.description}\n\nThis PR contains a template remediation note, not a generated code fix — see \`${path}\`.\n\n_Branch ${createdBranch ? 'created' : 'reused'} by the Agentic SDLC Platform demo._`,
    );

    res.status(200).json({
      ok: true,
      reused: false,
      prUrl: pr.html_url,
      prNumber: pr.number,
      branch,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    res.status(502).json({ ok: false, error: message });
  }
}
